name: Build and Deploy
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
          submodules: true
          token: ${{ secrets.ACTION_KEY }}
          
    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build using Gradle
      run: |
        ./gradlew copyApplicationYml
        ./gradlew bootJar
      
    - name: Upload Jars
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jars
        path: build/libs/*.jar
    
  Delivery:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Install sshpass   
      run: sudo apt install sshpass
    
    - name: Download Jars
      uses: actions/download-artifact@v2.1.1
      with:
        name: jars
        
    - name: Deliver Jars to Goorm Server using SCP
      run: sshpass -p ${{ secrets.SSH_KEY }} scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} *.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_TARGET_IP }}:~/deploy/

    - name: Deliver Jars to NCP Server using SCP
      run: sshpass -p ${{ secrets.SSH_KEY_NCP }} scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT_NCP }} *.jar ${{ secrets.SSH_USERNAME_NCP }}@${{ secrets.SSH_TARGET_IP_NCP }}:~/deploy/

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build, Delivery]
    steps:
    - name: Install sshpass   
      run: sudo apt install sshpass
      
    - name: Deploy - Goorm Server
      run: |
        sshpass -p ${{ secrets.SSH_KEY }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_TARGET_IP }} "sudo fuser -k 8080/tcp || true"
        sshpass -p ${{ secrets.SSH_KEY }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_TARGET_IP }} "sudo nohup java -jar -Duser.timezone=Asia/Seoul ~/deploy/*.jar > ~/nohup.log 2>&1 &"
        sshpass -p ${{ secrets.SSH_KEY }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_TARGET_IP }} "sudo echo "[$(date)] Deploy done" >> deploy_log.txt"
      
    - name: Deploy - NCP Server
      run: |
        sshpass -p ${{ secrets.SSH_KEY_NCP }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_NCP }} ${{ secrets.SSH_USERNAME_NCP }}@${{ secrets.SSH_TARGET_IP_NCP }} "sudo fuser -k 8080/tcp || true"
        sshpass -p ${{ secrets.SSH_KEY_NCP }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_NCP }} ${{ secrets.SSH_USERNAME_NCP }}@${{ secrets.SSH_TARGET_IP_NCP }} "sudo nohup java -jar -Duser.timezone=Asia/Seoul ~/deploy/*.jar > ~/nohup.log 2>&1 &"
        sshpass -p ${{ secrets.SSH_KEY_NCP }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_NCP }} ${{ secrets.SSH_USERNAME_NCP }}@${{ secrets.SSH_TARGET_IP_NCP }} "sudo echo "[$(date)] Deploy done" >> deploy_log.txt"
        
        
